export enum ACTION_TYPES {
    FETCH_CARD_LIST = '@@CARD/FETCH_CARD_LIST',
    SET_CARD_LIST = '@@CARD/SET_CARD_LIST',
    FETCH_CARD_MAP = '@@CARD/FETCH_CARD_MAP',
    SET_CARD_MAP = '@@CARD/SET_CARD_MAP',
    ADD_CARD = '@@CARD/ADD_CARD',
    UPDATE_CARD_LIST_ID = '@@CARD/UPDATE_CARD_LIST_ID',
    DEL_CARD = '@@CARD/DEL_CARD',
}
