export enum ACTION_TYPES {
    SET_TOKEN = '@@AUTH/SET_TOKEN',
    FETCH_TOKEN = '@@AUTH/FETCH_TOKEN',
    CLEAR_TOKEN = '@@AUTH/CLEAR_TOKEN',
    SIGN_OUT = '@@AUTH/SIGN_OUT',
    FETCH_IS_SING_IN = '@@AUTH/FETCH_IS_SING_IN'
}
