export enum ACTION_TYPES {
    SET_BOARD = '@@BOARD/SET_BOARD',
    FETCH_BOARD = '@@BOARD/FETCH_BOARD',
    FETCH_BOARD_BY_ID = '@@BOARD/FETCH_BOARD_BY_ID',
    ADD_BOARD = '@@BOARD/ADD_BOARD',
    DEL_BOARD = '@@BOARD/DEL_BOARD'
}
